import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

/**
 * This interface defines the JSON payload we send TO AppSheet.
 * It must match your database columns.
 */
export interface AppSheetRecord {
  // id is not sent, it's generated by the database
  filename: string;
  url: string;
  type: string;
  createdby: string;
}

/**
 * This defines the expected JSON response FROM AppSheet
 */
export interface AppSheetResponse {
  // AppSheet often returns the rows it created
  Rows: AppSheetRecord[];
}

@Injectable({
  providedIn: 'root'
})
export class FileUploadService {

  // --- YOUR APPSHEET API DETAILS ---
  private appId = '9ec09e35-2a22-4a83-a4b4-dc81dc83b7aa';
  private accessKey = 'V2-JNg3X-ymSwi-TfTUn-73T2k-e4XVh-nJOeL-8FCpZ-l0Ulf';
  private tableName = 'capex_app'; // <-- You provided this
  
  // This is the correct AppSheet API endpoint
  private apiUrl = `https://www.appsheet.com/api/v2/apps/${this.appId}/tables/${this.tableName}/Action`;

  constructor(private http: HttpClient) {}

  addFileRecord(record: AppSheetRecord): Observable<AppSheetResponse> {
    
    // 1. Create the AppSheet API headers
    const headers = new HttpHeaders({
      'Content-Type': 'application/json',
      'ApplicationAccessKey': this.accessKey 
    });

    // 2. Create the JSON body
    // The AppSheet API requires this specific structure
    const payload = {
      "Action": "Add",
      "Properties": {
        "Locale": "en-US"
      },
      "Rows": [
        record // Your record is here
      ]
    };

    // 3. Send the POST request with the JSON payload
    return this.http.post<AppSheetResponse>(this.apiUrl, payload, { headers: headers });
  }
}